name: func-test

on:
  push:
    branches: [ master ]

jobs:
  func-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Verilator
      run: sudo apt-get install verilator
    - name: Run tests
      run: |
        cd $GITHUB_WORKSPACE/chisel
        sbt 'testOnly soc.AutoTest'